apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: hello-openshift-deployment
    labels:
      app: hello-openshift
      app.kubernetes.io/component: hello-openshift
      app.kubernetes.io/instance: hello-openshift
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        deployment: hello-openshift
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: hello-openshift
      spec:
        containers:
        - image: openshift/hello-openshift@sha256:aaea76ff622d2f8bcb32e538e7b3cd0ef6d291953f3e7c9f556c1ba5baf47e2e
          imagePullPolicy: IfNotPresent
          name: hello-openshift
          ports:
          - containerPort: 8888
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List