apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: hello-openshift
  name: hello-openshift
spec:
  port:
    targetPort: http1
  to:
    kind: Service
    name: hello-openshift-svc
    weight: 100
  wildcardPolicy: None