apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: test-job
  namespace: ansible-test
spec:
  tower_auth_secret: 'test-secret'
  job_template_name: 'Ping host'
  extra_vars:
    enable_gather_facts: 'true'