apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: test-job
  namespace: ansible-test
spec:
  tower_auth_secret: 'test-secret'
  job_template_name: 'haproxy-config'
  inventory: 'lb3'
  extra_vars:
    server_ip_1: '172.29.9.65'
    server_ip_2: '172.29.9.66'