apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: remove-self-provision
  namespace: default
  annotations:
    apps.open-cluster-management.io/git-path: assets/gitops
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: gitops-apps/acm-gitops-github
  placement:
    local: true