---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-openshift-namespace
  
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: hello-openshift-subscription
  namespace: hello-openshift-namespace
  labels:
    app: hello-openshift-app
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: assets/hello-openshift
spec:
  channel: hello-openshift-namespace/hello-openshift-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: allow-all

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: allow-all
  namespace: hello-openshift-namespace
  labels:
    app: hello-openshift-app
spec:
  clusterSelector: {}

---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: hello-openshift-channel
  namespace: hello-openshift-namespace
  labels:
    app: hello-openshift-app
spec:
  pathname: 'https://github.com/KennyMacCormik/acmtest.git'
  type: Git

---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: hello-openshift-app
  name: hello-openshift-application
  namespace: hello-openshift-namespace
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: hello-openshift-app
status: {}