---
apiVersion: v1
kind: Namespace
metadata:
  name: acm-simple-app
  labels:
    acm: demo

---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: federation
  namespace: acm-simple-app
spec:
  pathname: 'https://github.com/dsevost/acm-demo'
  type: Git

---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: httpd
  namespace: acm-simple-app
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - httpd
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: httpd
  name: cluster1only
  namespace: acm-simple-app
spec:
  clusterSelector:
    matchLabels:
      clusterid: cluster1

---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: httpd
  namespace: acm-simple-app
  labels:
    app: httpd
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: application-portability/lab-4-assets
spec:
  channel: acm-simple-app/federation
  placement:
    placementRef:
      kind: PlacementRule
      name: cluster1only